import Head from 'next/head';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { useState } from 'react';
import React from 'react';
import { mjmlHtml } from './api/emailTemplate';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const [mode, setMode] = useState<'pc' | 'mobile'>('pc');
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div>
          <p>💌 MJML in ⏭️ Next</p>
          <iframe srcDoc={mjmlHtml}></iframe>
        </div>
      </main>
    </>
  );
}
